### ISSUE TITLE
client-side demo

### ISSUE THREAD

**Issue by pbuzdin** [estrattonbailey/operator#9]
Hi there!

Is there any demo?
Does it work client-side way?

**Comment by estrattonbailey** [comment]
Hey @pbuzdin! My bad, sorry for the delay. 

I've been working on a demo for a while, just can't find the time to finish it. There are some sites in the wild that I've built with it though, for example [this one](https://loveadorned.com/pages/designers).

And yes, it is purely client-side. Meant for Wordpress, Shopify, static sites, etc.
